# Generated by Django 4.0 on 2023-08-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('activa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrpicion', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('oferta', models.BooleanField()),
                ('precio_oferta', models.IntegerField()),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
