# Generated by Django 4.0 on 2023-09-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductosApp', '0002_productoimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descrpicion',
            new_name='descripicion',
        ),
    ]
