# Generated by Django 4.0 on 2023-09-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductosApp', '0003_rename_descrpicion_producto_descripicion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripicion',
            new_name='descripcion',
        ),
    ]
