# Generated by Django 4.0 on 2023-09-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductosApp', '0007_comentarioproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarioproducto',
            old_name='producto',
            new_name='id_producto',
        ),
        migrations.RenameField(
            model_name='productoimg',
            old_name='producto',
            new_name='id_producto',
        ),
    ]
