# Generated by Django 4.0 on 2023-09-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompraApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='contacto',
            field=models.IntegerField(default=999999999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
