# Generated by Django 4.0 on 2023-09-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompraApp', '0002_compra_ciudad_compra_contacto_compra_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetalle',
            name='linea',
            field=models.IntegerField(default=1),
        ),
    ]
