# Generated by Django 4.0 on 2023-09-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompraApp', '0003_compradetalle_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='contacto',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
