# Generated by Django 4.0 on 2023-09-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductosApp', '0003_rename_descrpicion_producto_descripicion'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('CarritoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritodetalle',
            name='producto',
        ),
        migrations.AddField(
            model_name='carritodetalle',
            name='id_carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CarritoApp.carrito'),
        ),
        migrations.AddField(
            model_name='carritodetalle',
            name='id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductosApp.producto'),
        ),
        migrations.AddField(
            model_name='carritodetalle',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carritodetalle',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='carritodetalle',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='carritodetalle',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='carritodetalle',
            name='linea',
            field=models.IntegerField(default=1),
        ),
    ]
